// ── Terminals ──────────────────────────────────────────────
NAME      : /[a-zA-Z_][a-zA-Z0-9_]*/
NUMBER    : /[0-9]+(\.[0-9]+)?/
STRING    : /\"[^\"]*\"|\'[^\']*\'/
COMMENT   : /\/\/[^\n]*/

array: "[" expr ("," expr)* "]"
bool: "true" -> bool_true
    | "false" -> bool_false


map_obj: expr ":" expr
map: "{" map_obj ("," map_obj)* "}"

// ── Entry point ────────────────────────────────────────────
?start        : statement*

declare_types: "int" -> inttype
            | "string" -> strtype
            | "bool" -> booltype
            | "array" -> arraytype
            | "map" -> maptype

// ── Statements ─────────────────────────────────────────────
?statement    : local_decl
            | fn_def
            | return_stmt
            | while_stmt
            | for_stmt
            | foritem_stmt
            | expr_stmt
            | decl
            | if_stmt

// ── Variable declaration ───────────────────────────────────
local_decl   : "local" declare_types NAME "=" expr
decl: NAME "=" expr

// ── Function definition ────────────────────────────────────
fn_def       : declare_types "fn" NAME "(" param_list ")" block
            | declare_types "fn" NAME "(" ")" block -> fn_def_nargs

param_list : param ("," param)*
param      : declare_types NAME


// ── Return ─────────────────────────────────────────────────
return_stmt  : "return" expr?

// ── While ──────────────────────────────────────────────────
while_stmt   : "while" "(" condition ")" block

// ── For loops ──────────────────────────────────────────────
for_stmt     : "for" "(" declare_types NAME "in" expr ")" block
foritem_stmt : "foreach" "(" declare_types NAME "," declare_types NAME "in" expr ")" block

// ── If ─────────────────────────────────────────────────────

if_stmt: "if" "(" condition ")" block elseif_stmt* elsestmt?
elseif_stmt: "elseif" "(" condition ")" block
elsestmt: "else" block

// ── Block ──────────────────────────────────────────────────
block        : "{" statement* "}"

// ── Expressions ────────────────────────────────────────────
?expr_stmt    : expr
?expr         : fn_call | NUMBER | STRING | array | map | member_access | bool
            | expr "+" expr -> add_stmt
            | expr "-" expr -> sub_stmt
            | expr "*" expr -> mul_stmt
            | expr "/" expr -> div_stmt


?comparison: expr "==" expr -> equ
            | expr "!=" expr -> nequ
            | expr ">=" expr -> gte
            | expr "<=" expr -> lte
            | expr ">"  expr -> gt
            | expr "<"  expr -> lt
            | expr

?condition: or 

?or: and ("or" or) -> or_cond | and
?and: not ("and" and) -> and_cond | not
?not: "not" comparison -> not_cond | comparison 


// ── Function call ──────────────────────────────────────────
fn_call      : member_access "(" arg_list? ")"
member_access: NAME ("." NAME)*
arg_list     : expr ("," expr)*

// ── Ignored tokens ─────────────────────────────────────────
%ignore /[ \t\r\n]+/
%ignore COMMENT